language: ruby
rvm: 2.1

# Does this in order to use Travis' new infrastructure
sudo: false

branches:
  except:
    - master

# Well, has to cache this slow bundler
cache: bundler

before_install:
  - openssl aes-256-cbc -K $encrypted_e9c8ab5869f3_key -iv $encrypted_e9c8ab5869f3_iv -in .deploy_key.enc -out .deploy_key -d
  - chmod 600 .deploy_key

script: ". ./travis_build.sh"
env:
  global:
    - GH_REPO: github.com/tklarryonline/tklarryonline.github.io.git
    - secure: "Ny1FgdVjW0W6++X5UPP3Zuw399u6OiaN2wtbJL2zwHgWHxlp7uVU4pa6vSyDZXlMkq0NSCZBBXx6V4f54HYRmPsNgEGSTcBUW6/WTgluCyXpyLds0pvTp3UlmKCs0aP3kU5ikIuvvWUtiBp980KsVX3TlW6MDUtoaxqmDVRJkFk="
