# Global config
destination:      tklarryonline
timezone:         Asia/Ho_Chi_Minh
exclude:          [Gemfile, Gemfile.lock]
encoding:         UTF-8

# Serve commands
port:             1616

# Personal stuff
title:            tklarryonline.me
description:      thinking and hacking
url:              tklarryonline.github.io
signoff:          Luan Nguyen Thanh
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links: 
  - name:         Blog
    url:          /blog/
  - name:         About TK
    url:          /about/
  - name:         Bookshelf
    url:          /books/
  - name:         Email
    url:          mailto:luan@tklarryonline.me

pygments:         true
permalink:        /blog/:title/
markdown:         redcarpet

sass:
    syntax: scss
    style: compressed
