# Global config
destination:      tklarryonline
timezone:         Asia/Ho_Chi_Minh
exclude:          [Gemfile, Gemfile.lock]
encoding:         UTF-8

# Serve commands
port:             1616

# Personal stuff
title:            tklarryonline.me
description:      thinking and hacking
url:              http://tklarryonline.me
signoff:          Luan Nguyen Thanh
disqus_shortname: tklarryonline
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name: Home
    url: /
    fa: home
  - name:         Work
    url:          /work/
    fa: laptop
  - name:         Blog
    url:          /blog/
    fa: lightbulb-o
  - name:         Bookshelf
    url:          /books/
    fa: book
  - name:         Email
    url:          mailto:luan@tklarryonline.me
    fa: envelope-o

home-main-links:
  - name:         Work
    url:          /work/
    description:  see my work
  - name:         Blog
    url:          /blog/
    description:  read my blog
  - name:         Email
    url:          mailto:luan@tklarryonline.me
    description:  talk to me

pygments:         true
permalink:        /blog/:title/
markdown:         redcarpet

sass:
    syntax: scss
    style: compressed
